on:
  push:
    branches: 
      - master

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: set environment variables
        uses: allenevans/set-env@v1.0.0
        with:
          TAG: $(node pkg.js)
#      - name: export tag
#        run: |
#          export TAG="$(node pkg.js)"
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${TAG}
          release_name: Release ${TAG}
          body: |
          draft: false
          prerelease: false
